# Generated by Django 5.2.17 on 2026-08-28 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_check_in', models.DateField()),
                ('planned_check_out', models.DateField()),
                ('has_car', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('reserved', 'Reservado'), ('checked_in', 'Hospedado'), ('checked_out', 'Check-out realizado')], default='reserved', max_length=20)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='guests.guest')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('planned_check_out__gt', models.F('planned_check_in'))), name='check_out_after_check_in')],
            },
        ),
    ]
